In [32]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

In [39]:
df = pd.read_csv("../data/raw/FreddieMac.csv")

print(df.shape)
df.head()

(291451, 28)

/var/folders/92/ptnjnlq917lb_tj60r_31src0000gn/T/ipykernel_71317/2489300305.py:1: DtypeWarning: Columns (0: PostalCode) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../data/raw/FreddieMac.csv")

,CreditScore,FirstPaymentDate,FirstTimeHomebuyer,MaturityDate,MSA,MIP,Units,Occupancy,OCLTV,DTI,OrigUPB,LTV,OrigInterestRate,Channel,PPM,ProductType,PropertyState,PropertyType,PostalCode,LoanSeqNum,LoanPurpose,OrigLoanTerm,NumBorrowers,SellerName,ServicerName,EverDelinquent,MonthsDelinquent,MonthsInRepayment
0,0,199902,N,202901,16974,25,1,O,89,27,117000,89,6.750,T,N,FRM,IL,SF,60400,F199Q1268030,P,360,2,FL,WASHINGTONMUTUALBANK,0,0,52
1,0,199902,N,202901,19740,0,1,O,73,17,109000,73,6.500,R,N,FRM,CO,SF,80200,F199Q1015092,N,360,1,FT,CHASEHOMEFINANCELLC,0,0,144
2,0,199902,N,202901,29940,0,1,O,75,16,88000,75,6.875,T,N,FRM,KS,SF,66000,F199Q1266886,N,360,2,FL,WASHINGTONMUTUALBANK,0,0,67
3,0,199902,N,202901,31084,0,1,O,76,14,160000,76,6.875,R,N,FRM,CA,SF,90700,F199Q1178167,N,360,2,GM,GMACMTGECORP,0,0,35
4,0,199902,N,202901,35644,0,1,O,78,18,109000,78,7.125,R,N,FRM,NJ,SF,7600,F199Q1178517,N,360,2,GM,GMACMTGECORP,0,0,54

In [40]:
print(df.shape)

df.info()

(291451, 28)
<class 'pandas.DataFrame'>
RangeIndex: 291451 entries, 0 to 291450
Data columns (total 28 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   CreditScore         291451 non-null  int64
 1   FirstPaymentDate    291451 non-null  int64
 2   FirstTimeHomebuyer  291451 non-null  str
 3   MaturityDate        291451 non-null  int64
 4   MSA                 291451 non-null  str
 5   MIP                 291451 non-null  int64
 6   Units               291451 non-null  int64
 7   Occupancy           291451 non-null  str
 8   OCLTV               291451 non-null  int64
 9   DTI                 291451 non-null  int64
 10  OrigUPB             291451 non-null  int64
 11  LTV                 291451 non-null  int64
 12  OrigInterestRate    291451 non-null  float64
 13  Channel             291451 non-null  str
 14  PPM                 291451 non-null  str
 15  ProductType         291451 non-null  str
 16  PropertyState       291451 non-null  str
 17  PropertyType        291451 non-null  str
 18  PostalCode          291451 non-null  object
 19  LoanSeqNum          291451 non-null  str
 20  LoanPurpose         291451 non-null  str
 21  OrigLoanTerm        291451 non-null  int64
 22  NumBorrowers        291451 non-null  str
 23  SellerName          266457 non-null  str
 24  ServicerName        291451 non-null  str
 25  EverDelinquent      291451 non-null  int64
 26  MonthsDelinquent    291451 non-null  int64
 27  MonthsInRepayment   291451 non-null  int64
dtypes: float64(1), int64(13), object(1), str(13)
memory usage: 62.3+ MB

In [41]:
data = df.copy()

print(data.shape)

(291451, 28)

In [42]:
data["CreditScore"] = data["CreditScore"].replace(0, np.nan)

data["CreditScore"] = data["CreditScore"].fillna(
    data["CreditScore"].median()
)

data["CreditScore"].describe()

count    291451.000000
mean        711.862056
std          51.196660
min         335.000000
25%         676.000000
50%         717.000000
75%         753.000000
max         849.000000
Name: CreditScore, dtype: float64

In [43]:
data["SellerName"] = data["SellerName"].fillna(
    data["SellerName"].mode()[0]
)

data["SellerName"].isnull().sum()

np.int64(0)

In [44]:
drop_cols = [
    "LoanSeqNum",
    "MonthsDelinquent"
]

data.drop(columns=drop_cols, inplace=True)

print(data.shape)

(291451, 26)

In [45]:
data["EverDelinquent"].value_counts(normalize=True)

EverDelinquent
0    0.802152
1    0.197848
Name: proportion, dtype: float64

In [46]:
data["FirstPaymentDate"] = pd.to_datetime(
    data["FirstPaymentDate"].astype(str),
    format="%Y%m"
)
data["MaturityDate"] = pd.to_datetime(
    data["MaturityDate"].astype(str),
    format="%Y%m"
)

In [47]:
data[
    ["FirstPaymentDate", "MaturityDate"]
].head()

  FirstPaymentDate MaturityDate
0       1999-02-01   2029-01-01
1       1999-02-01   2029-01-01
2       1999-02-01   2029-01-01
3       1999-02-01   2029-01-01
4       1999-02-01   2029-01-01

In [48]:
data["LoanAgeMonths"] = (
    (data["MaturityDate"].dt.year - data["FirstPaymentDate"].dt.year) * 12
    +
    (data["MaturityDate"].dt.month - data["FirstPaymentDate"].dt.month)
)
data["LoanAgeMonths"].describe()

count    291451.000000
mean        358.835375
std           2.286939
min         300.000000
25%         359.000000
50%         359.000000
75%         359.000000
max         360.000000
Name: LoanAgeMonths, dtype: float64

In [49]:
data["LoanAgeMonths"].value_counts().sort_index()

LoanAgeMonths
300         6
301         5
302         4
303         4
304        12
305        15
306        20
307        22
308        15
309        23
310        11
311        77
312        20
313        18
314        14
315        12
316        20
317        14
318        13
319        17
320         9
321        10
322        11
323        88
324        14
325        19
326        25
327        44
328        29
329        44
330        23
331        27
332        21
333        43
334        40
335       205
336        51
337        38
338        30
339        34
340        27
341        20
342        24
343        19
344        18
345        25
346        16
347        94
348        29
349        40
350        64
351        61
352        83
353       434
354        51
355        39
356        47
357        35
358       103
359    289073
360         2
Name: count, dtype: int64

In [50]:
data["FirstPaymentDate"].value_counts().head(20)

FirstPaymentDate
1999-05-01    104071
1999-04-01     91152
1999-03-01     89401
1999-02-01      2300
1999-06-01      2083
1999-10-01       411
1999-11-01       411
1999-09-01       294
1999-08-01       131
1999-12-01       131
2000-01-01       106
1999-07-01        90
2000-02-01        85
2000-03-01        63
2000-04-01        48
2000-05-01        41
2001-03-01        35
2001-02-01        33
2001-11-01        33
2001-12-01        30
Name: count, dtype: int64

In [51]:
data["MaturityDate"].value_counts().head(20)

MaturityDate
2029-04-01    104210
2029-03-01     91059
2029-02-01     89304
2029-01-01      2282
2029-05-01      2067
2029-09-01       298
2029-10-01       266
2029-08-01       211
2029-11-01       111
2029-07-01        92
2029-12-01        90
2030-01-01        81
2027-02-01        76
2029-06-01        67
2027-03-01        60
2027-04-01        58
2030-02-01        57
2028-08-01        55
2030-03-01        53
2028-07-01        46
Name: count, dtype: int64

In [52]:
drop_cols = [
    "FirstPaymentDate",
    "MaturityDate",
    "LoanAgeMonths"
]

data.drop(
    columns=drop_cols,
    inplace=True
)

print(data.shape)

(291451, 24)

In [54]:
data.to_csv(
    "../data/processed/freddie_processed.csv",
    index=False
)

print("Dataset saved successfully.")

Dataset saved successfully.